application: pytradebot2
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: page.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest